# Copyright 2021 The Authors
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
'''
TTPython programs are dataflow graphs, composed of nodes or 'Scheduling Quanta'
(SQs). SQs in the graph are connected by arcs, which generlly correspond to
variable names in the TTPython program

The graph is generated by our ``Compiler`` based pythonic function that has been
given the 'GRAPHify' decorator. The graph also includes additional constructs
like a set of clocks and constraints, which are generally described using 'with'
constructs
'''

from . import DebugLogger
from collections import defaultdict

from typing import List, DefaultDict, Tuple, Set, Dict, Any, TYPE_CHECKING
if TYPE_CHECKING:
    from .SQ import TTSQ

logger = DebugLogger.get_logger('Graph')


class TTGraph:
    '''
    TTGraphs are created as empty graphs, containing only empty instance
    variables that will be filled in during the compilation process.

    The graph contains the set of available base SQ functions, a list of those
    SQs as they are implemented within the graph (including the arc
    connections), a set of clocks, a set of symbols, a set of input or 'trigger'
    arcs, and a set of constraints to apply to SQs (or groups thereof).

    '''

    def __init__(self, name, trigger_port_name, source_vars, sqs,
                 clock_dictionary, constraints):
        self.graph_name = name
        self.sqs: List['TTSQ'] = sqs
        self.clock_dictionary = clock_dictionary
        self.trigger_port_name = trigger_port_name
        self.source_vars: Dict[str, Any] = source_vars
        self.flattened_constraints = constraints
        # Deadline requirements (populated by _embed_deadline_requirements)
        self.deadline_requirements = None

        # Multitenancy: Hyperperiod for time-slicing schedules
        self.hyperperiod = None  # LCM of all SQ periods in milliseconds

        # Deployment specification: resolved device instances from compilation.
        # Populated by Compiler when deployment YAML is provided at compile time.
        # Travels with the graph pickle so RuntimeManager reads it directly,
        # eliminating the need to load a separate deployment YAML at runtime.
        # Format: {device_id: {'type': str, 'cpu_speed': float, 'memory_size': int,
        #          'memory_mb': int, 'cpu_cores': int, 'compute_slots': int,
        #          'has_gpu': bool, 'power_active': float, 'power_idle': float,
        #          'components': dict, 'location': str}}
        self.deployment_spec = {}

        # Network topology: resolved link specs from compilation.
        # Format: {(device_a, device_b): {'latency': float, 'bandwidth': float}}
        # Bidirectional — both (a,b) and (b,a) stored.
        self.network_spec = {}

    # returns a map of input port to sq with its port num for each sq
    def get_ipp_to_sq_dict(self) -> DefaultDict[str, Set[Tuple['TTSQ', int]]]:
        ipp_to_sq = defaultdict(set)
        for sq in self.sqs:
            for port_num, ipp in enumerate(sq.get_ipps()):
                ipp_to_sq[ipp.data_name].add((sq, port_num))

        return ipp_to_sq
    
    def get_dag(self):
        """
        Build and cache a networkx DiGraph representing the dataflow DAG.
        
        Nodes carry the SQ object as an attribute. Edges represent
        dataflow dependencies derived from output/input port matching
        (opp.data_name → ipp.data_name).
        
        Cached on first call — subsequent calls return the same graph.
        
        :return: networkx.DiGraph with SQ names as nodes
        """
        if hasattr(self, '_cached_dag') and self._cached_dag is not None:
            return self._cached_dag
        
        import networkx as nx
        
        G = nx.DiGraph()
        sqs_list = self.sqs if isinstance(self.sqs, list) else list(self.sqs.values())
        
        for sq in sqs_list:
            G.add_node(sq.sq_name, sq=sq)
        
        ipp_to_sq = self.get_ipp_to_sq_dict()
        for sq in sqs_list:
            for opp in sq.opps:
                data_name = opp.data_name
                if data_name in ipp_to_sq:
                    for dest_sq, port_num in ipp_to_sq[data_name]:
                        if dest_sq.sq_name != sq.sq_name:
                            G.add_edge(sq.sq_name, dest_sq.sq_name)
        
        self._cached_dag = G
        return G

    def source_var_names(self):
        '''
        Generate a dictionary of the input arcs to the graph (i.e., the arcs
        that must be given some initial value at runtime to trigger the rest of
        the graph to start). Those arcs have no source SQ, and must have
        destination SQs
        '''
        return self.source_vars

    def json_graph_inputs(self):
        inputs = {}
        for _, (symbol, arc) in enumerate(self.input_arc_dict().items()):
            inputs[symbol] = arc.arc_id()
        return inputs

    def json_graph_outputs(self):
        outputs = {}
        for _, (symbol, arc) in enumerate(self.output_arc_dict().items()):
            outputs[symbol] = arc.arc_id()
        return outputs

    def json_clocks(self):
        j = []
        for _, (_, clockspec) in enumerate(self.clock_dictionary.items()):
            j.append(clockspec.json())
        return j

    def json_port_map(self):
        j = []
        for _, (_, arc) in enumerate(self.symbol_table.items()):
            j.append({'port_name': arc.arc_id(), 'type': 'dynamic'})
        return j

    def json(self):
        j = []
        json_sqs = []
        for this_sq in self.sq_list:
            json_sqs.append(this_sq.json())
        j.append({
            'graph_id':
            self.graph_name,
            'graph_inputs':
            self.json_graph_inputs(),
            'graph_outputs':
            self.json_graph_outputs(),
            'clocks':
            self.json_clocks(),
            'SQs':
            json_sqs,
            'port_map':
            self.json_port_map(),
            'flattened_constraints':
            [c.json() for c in self.flattened_constraints]
        })
        return j

    def set_flattened_constraints(self, constraints):
        self.flattened_constraints = constraints
